#!/usr/bin/env bash

#
# Defaults
#

VERSION="0.0.1"
VERBOSE=

#
# Output usage
#

usage() {
cat << EOF
Usage:
  
  ${0##*/} [options] [arguments]

Options:
  -v, --verbose     Verbose
  -V, --version     Current version triplet
  -h, --help        Help information
EOF
}

#
# Install a seed.
# 
# <name>
#

install() {
  if [ $VERBOSE ]; then echo installing $1; fi
}

#
# Parse arguments
#

while [[ $# -gt 0 ]]; do
  token=$1; shift
  case $token in
    -v|--verbose) VERBOSE=1 ;;
    -V|--version) echo $VERSION ;;
    -h|--help) usage ;;
    install) install $1 ;;
  esac
done
