#!/usr/bin/env bash

#
# Defaults
#

VERSION=0.0.1
SEED_DIR=seeds
VERBOSE=

#
# Output usage.
#

usage() {
cat << EOF
Usage:
  
  ${0##*/} [options] [arguments]

Options:
  -v, --verbose     Verbose
  -V, --version     Current version triplet
  -h, --help        Help information
EOF
}

#
# Abort with the given <msg ...>
# 
# <msg ...>
#

abort() {
  echo $* && exit 1
}

#
# Log the given <msg ...> when $VERBOSE is true.
# 
# <msg ...>
#

log() {
  if [ $VERBOSE ]; then echo ... $*; fi
}

#
# Install a seed <name>
# 
# <name>
#

install() {
  if [ ! $1 ]; then abort seed name required.; fi
  log locating $1.yml
  if [ ! -f "$SEED_DIR/$1.yml" ]; then abort failed to locate $1.yml; fi
  local release=$(cat "$SEED_DIR/$1.yml" | grep release | awk '{ print $2 }')
  local version=${2-$release}
  log fetching $1.yml version $version
  cat "$SEED_DIR/$1.yml" | grep path | awk '{ print $2 }' | sed 's/{version}/FOO/'
}

#
# Parse arguments.
#

while [[ $# -gt 0 ]]; do
  arg=$1; shift
  case $arg in
    -v|--verbose) VERBOSE=1 ;;
    -V|--version) echo $VERSION ;;
    -h|--help) usage ;;
    --*) echo invalid option $arg. Use --help for more information ;;
    install) install $* ;;
  esac
done
